# **Lab 1: Introduction to Python for Data Science**

In [ ]:
# Demonstrating basic data types
int_var = 10 # Integer
float_var = 20.5 # Float
string_var = "Hello, Python!" # String
list_var = [1, 2, 3, 4] # List
tuple_var = (5, 6, 7, 8) # Tuple
set_var = {1, 2, 2, 3} # Set (removes duplicates)
dict_var = {'a': 1, 'b': 2,'c': 3} # Dictionar
print('Integer: {int_var}')
print('Float: {float_var}')
print('String: {string_var}')
print('List: {list_var}')
print('Tuple: {tuple_var}')
print('Set: {set_var}')
print('Dictionary: {dict_var}')

Integer: {int_var}
Float: {float_var}
String: {string_var}
List: {list_var}
Tuple: {tuple_var}
Set: {set_var}
Dictionary: {dict_var}

In [ ]:
# Arithmetic operations
a, b = 15, 4
print('Addition:', a + b)
print('Subtraction:', a - b)
print('Multiplication:', a * b)
print('Division:', a / b)
# String manipulation
text = 'Data Science'
print('Uppercase:', text.upper())
print('Reversed:', text[::-1])
# List slicing
my_list = [10, 20, 30, 40, 50]
print('First three elements:', my_list[:3])
print('Last two elements:', my_list[-2:])

Addition: 19
Subtraction: 11
Multiplication: 60
Division: 3.75
Uppercase: DATA SCIENCE
Reversed: ecneicS ataD
First three elements: [10, 20, 30]
Last two elements: [40, 50]